name: sa_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+2
  cached_network_image: ^1.1.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DancingScript
      fonts:
      - asset: assets/fonts/dancing_script_regular.ttf
